# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75651cdc8c30c41be3a79ae167d524e33dff7d117e43dc194a011e29743471262a3459b6971080fdba63fc7ee470d05ae39e1896bd1c8be9f2e374fe0ba9a2b4

test:
  secret_key_base: 6976b6721ae3e2eb710900de09e577c22a376d9f4db7a17e3166b3442cb14b8bd8b84c42f54e24261d2f44c636c2438afe77151b634acaaa2edff403c0b6e6c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
